image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
    PYTHON: "python.exe"

build_script:
- cmd: >-
    python.exe --version
    python.exe -m pip install --user -r requirements.txt

    mkdir build

    cd build

    cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release

    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Debug --output-on-failure

