image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
    PYTHON: "python.exe"

build_script:
- cmd: >-
    set PATH=C:\\Python38-x64;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts;%PATH%

    "%PYTHON%" -m pip install --user -r requirements.txt

    mkdir build

    cd build

    cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release

    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Debug --output-on-failure

